# -*- coding: utf-8 -*-
"""nc_to_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdS-PySUcioV15RWs1pE-w86UIfMdyzd
"""

!pip install netCDF4
import os
import netCDF4 as nc
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
os.getcwd()

os.chdir('/content/')
os.getcwd()

import xarray as xr
import os
#add your directory here
local_storage_directory = '/content/snpp/'
netcdf_dir = local_storage_directory + 'ncn/'
csv_dir = local_storage_directory + 'CSV/'
files_to_convert = local_storage_directory
for filename in os.listdir(files_to_convert):
    name=files_to_convert + filename
    print(name)
    ds = xr.open_dataset(name)
    df = ds.to_dataframe()
    df.to_csv(csv_dir + filename[:-3] + '.csv')
    print(filename[:-3] + ' has been processed to .csv')
#once the files are creted in the folder there wil be a value error warning shown ignore the warning







#
 #   ds = xr.open_dataset('/content/snpp/viirs_eps_npp_aod_0.050_deg_20170101 (1).nc')
  #  df = ds.to_dataframe()
   # df.to_csv('/content/snpp/trail.csv')