# -*- coding: utf-8 -*-
"""WIND_trial .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQw3ISzG6f6ru2HtLWMFUsAYTXhUWQhl
"""

!pip install metpy
import metpy

import metpy.calc as mpcalc
from metpy.units import units
u = (-8) * units("m/s")

v = (2) * units("m/s")

print(mpcalc.wind_direction(u,v),convention='from')

metpy.calc.wind_speed(u, v)